<?php
namespace keli\opensdk;

use Hanson\Foundation\AbstractAPI;

class Api extends  AbstractAPI
{
    private $mch_id;
    private $appId;
    private $appSecret;
    const API = 'https://www.baidu.com';
    public function __construct($mch_id, $appId,$appSecret)
    {
        $this->mch_id = $mch_id;
        $this->appId = $appId;
        $this->appSecret = $appSecret;
    }
    public function request()
    {
        return parent::getHttp(); // TODO: Change the autogenerated stub
    }

    public function getToken($refresh = false)
    {


    }

}